### ISSUE TITLE
GO.R error

### ISSUE THREAD

**Issue by francicco** [gengit/FRAMA#1]
Hi,

I'm trying to run the test file, but I got this error:

```
Error in toTable(GOTERM) : object 'GOTERM' not found
```

where is the problem?
Thanks
F

**Comment by mrtnbns** [comment]
Hi francicco,

`GOTERM` ist part of the `GO.db` package, which provides the basis for the GO assignment. Looks like `GO.db` is not installed on your system. 

You can either run `./SETUP` to install missing R-packages or install the package(s) yourself in R:

```
# bioconductor 
source("http://bioconductor.org/biocLite.R")
mypackages = c("GO.db", "org.Hs.eg.db", "KEGG.db")
installme = mypackages[!(mypackages %in% installed.packages()[,"Package"])]
biocLite(installme)

# in case you have not installed other required packages too:
mypackages = c("plyr", "ggplot2", "reshape", "gridExtra", "grid")
installme = mypackages[!(mypackages %in% installed.packages()[,"Package"])]
install.packages(installme, repos =  "http://cran.us.r-project.org")
```

Hope that helps,
-- Martin

**Comment by francicco** [comment]
Great Martin,

Now it works, I thought I did install it.

On last quick question. Since I'm annotating a ant species, can I use a Drosophila Go annotation (hom.Dm.inp.db)?

thanks
F

**Comment by mrtnbns** [comment]
Actually, I haven't looked into the `*.inp.*` packages, but both `org.Dm.eg.db` and `org.Dm.inp.db` should work fine. 

However, regarding the gene annotation: there are mRNA sequences from closer related species available (_Apis mellifera_, _Polistes canadensis_, _Dinoponera quadriceps_). For example, _Dinoponera quadriceps_: ftp://ftp.ncbi.nlm.nih.gov/genomes/Dinoponera_quadriceps/RNA/rna.gbk.gz

-- Martin

**Comment by francicco** [comment]
But I do have to use those species as reference right?
So include them in an table of orthologs and use one of them as reference right?

**Comment by mrtnbns** [comment]
I don't know whether I understand you correctly. You can either use one of the species I mentioned as reference (without any orthologs), but then you would have to go without GO and KEGG annotation, because non of these are available from Bioconductor. Or you use Drosophila, then you get GO and KEGG. If you use Drosophila, you can support FRAMA with an ortholog table with assigned orthologs from other species to drosophila transcripts. Those orthologs are then used to improve coding sequence inference.

**Comment by francicco** [comment]
Yes, exactly,

1) I put Drosophila along the other ants
2) compute the ortholog table using D. melanogaster as referece
3) annotate genes with GO and KEGG.

or 

1) Use only ants
2) compute the ortholog table using the closest species as reference
3) can't directly compute GO annotation

Is that right?
thank you
F

**Comment by mrtnbns** [comment]
Exactly.
