### ISSUE TITLE
dir2comp

### ISSUE THREAD

**Issue by francicco** [gengit/FRAMA#2]
Hi Martin,

I'm running a test run with my data. I had some problem running trinity from FRAMA, so I decided to use my trinity run. In particular I used the `genome guide mode`, and i renamed the trinity assembly accordingly (`Trinity.fasta`).

Now, after **Repeat masking assembly** and several **Blast** searches FRAMA runs best bidirectional hits, single best hits and misassembled contigs. After this step it gives an error while trying to build the binary of dir2comp.index, in order to do that it needs `dir2comp.csv`, which is missing... 

How I fix this?
Thanks
F

**Comment by mrtnbns** [comment]
Hi francicco,

FRAMA currently relies on the intermediate output of Trinity. That output comprises the subset of reads that were aligned to a specific component graph. FRAMA  aligns those reads to the contig/scaffold and uses the alignment information (coverage, poly(A)s) to aid the mRNA boundary detection. 

It was convenient to align the subset of reads that Trinity already assigned to a component in order to avoid realigning the whole read input. However, I can implement a solution which aligns the complete read input and does not rely on the intermediate output, but not any time soon (> 2 weeks).

What exactly was the problem running Trinity from FRAMA? Guessing from your last issue, FRAMA is at least able to call Trinity.

**Comment by francicco** [comment]
Hi,

Thanks for the reply. Running Trinity from FRAMA using paired ends do not work, at least with these settings in the config file:

```
OPT_TRINITY   := --seqType fq --max_memory 10G --CPU 10
OPT_READTYPE  := pe
OPT_LIBRARY   := FR
OPT_BUTTERFLY := --max_memory 10G
```

F

**Comment by mrtnbns** [comment]
In case of paired end data, pairs of files belonging together must have the same name and have the suffixes "_R1" or "_R2" (for example: sampleA_R1.fq, sampleA_R2.fq, sampleB_R1.fq, sampleB_R2.fq)

Do you still have the logfiles? These should give a hint about what went wrong: 

```
OUTPUT/log/inchworm.log
OUTPUT/log/chrysalis.log
```

**Comment by francicco** [comment]
I rename read file like that: sampleA_R1.fq, sampleA_R2.fq

Trinity.log file says:

`Error, need either options 'left' and 'right' or option 'single' or 'genome_guided_bam'`

**Comment by francicco** [comment]
I have to say that the test run goes properly, but it's single end.

**Comment by mrtnbns** [comment]
Sounds like FRAMA could not find the read files. Did you specify the absolute path to the READ_DIR?

```
READ_DIR          := /your/path/to/read_files
```

Running FRAMA in verbose mode shows you the actual program calls. This might reveal some problems

```
FRAMA your_config.cfg verbose
```

Sorry, the README seems to be outdated. Please specify the library type via Trinity parameter like this:

```
OPT_TRINITY   := --seqType fq --max_memory 10G --CPU 10 --SS_lib_type FR
OPT_READTYPE  := pe
OPT_BUTTERFLY := --max_memory 10G
```

**Comment by francicco** [comment]
The variable for the read path is right.

These are the variable for trinity settings:

```
OPT_TRINITY   := --seqType fq --max_memory 10G --CPU 10 --SS_lib_type FR
OPT_READTYPE  := pe
OPT_BUTTERFLY := --max_memory 10G
```

and this is the log using verbose:
`/home/lv70640/c7701100/software/trinityrnaseq-2.1.1/Trinity --output /global/lv70640/c7701100/Projects/Talp_FRAMA_annotation/trinity/ --left  --right  --seqType fq --max_memory 10G --CPU 10 --SS_lib_type FR --no_cleanup --CPU 15`

left and right setting are empty

**Comment by mrtnbns** [comment]
Everything looks fine. If your read files end with on of these  `*.fq, *.fastq, *.fq.gz, *.fastq.gz` extension, it should work.

**Comment by francicco** [comment]
`sampleA_R1.fq` and `sampleA_R2.fq`

**Comment by francicco** [comment]
But this is not a big deal since I can run Trinity by myself, the problem is whether the genome guided strategy is going to work...

**Comment by mrtnbns** [comment]
I haven't used the genome guided option yet, but if you keep the intermediate files and move the Trinity output to the FRAMA output directory, it should work. I can try test it next week, too.

**Comment by francicco** [comment]
I'm doing it now, I'll let you know in a couple of hours, I'm coping the run from a cluster to the other.

Thanks for now, anyways!

**Comment by mrtnbns** [comment]
Related to [issue 3](https://github.com/gengit/FRAMA/issues/3). Solved.
