### ISSUE TITLE
Error during example run

### ISSUE THREAD

**Issue by Andy-B-123** [gengit/FRAMA#7]
Hi,

I have FRAMA installed on a computing cluster here at my work. I ran FRAMA using the example data and am getting the following output:

```
18-02-21 16:50:35 [INF] Starting FRAMA (v20171213)
18-02-21 16:50:35 [OUT]    /flush1/bac050/FRAMA/example/paired/output/parameters.cfg [parameter file]
18-02-21 16:50:35 [OUT]    /flush1/bac050/FRAMA/example/paired/output [output directory]

18-02-21 16:50:35 [INF] Checking required software and modules (consult log file in case of errors)
18-02-21 16:50:35 [LOG]    /flush1/bac050/FRAMA/example/paired/output/logs/000_software_check.log

perl init.pl ../setup/programs.yaml > /flush1/bac050/FRAMA/example/paired/output/logs/000_software_check.log
18-02-21 16:50:36 [INF] Creating directories

18-02-21 16:50:36 [INF] Assembly complete.
18-02-21 16:50:36 [INF] Primary processing complete.

18-02-21 16:50:36 [INF] BLAST
18-02-21 16:50:36 [INF] query=assembly database=reference
18-02-21 16:50:36 [LOG]    /flush1/bac050/FRAMA/example/paired/output/logs/054_blast_trin2cds.log
18-02-21 16:50:36 [OUT]    /flush1/bac050/FRAMA/example/paired/output/blast/raw_CDS_trin2ref.csv

perl parallel_blast.pl -q /flush1/bac050/FRAMA/example/paired/output/assembly/Trinity_preprocessed.masked.fa -db /flush1/bac050/FRAMA/example/paired/output/reference/ref_transcriptome_cds.masked.fa -o /flush1/bac050/FRAMA/example/paired/output/blast/raw_CDS_trin2ref.csv -j 20 -format tabular -engine parallel -path bin=/ -flavor genblasta -parameter '-p F -f T -g T -a 0.5 -d 200 -r 3 -c 0.2 -e "1e-5 -r 1 -q -3 -G 2 -E 2 -W 9 -b 50 -b 50 -a 1"' > /dev/null 2> /flush1/bac050/FRAMA/example/paired/output/logs/054_blast_trin2cds.log
Makefile:516: recipe for target '/flush1/bac050/FRAMA/example/paired/output/blast/raw_CDS_trin2ref.csv' failed

Please check error messages and consult log files.
```

The only associated error message I have is:
make: *** [/flush1/bac050/FRAMA/example/paired/output/blast/raw_CDS_trin2ref.csv] Error 25
make: *** Deleting file '/flush1/bac050/FRAMA/example/paired/output/blast/raw_CDS_trin2ref.csv'

I am unsure of what is causing the error. It looks as though the problem comes at perl line. I am running perl version 5.24.0 here. 

I can't seem to find any log or error files apart from the above. Please let me know if you've come across this before and if it might be something related to the set-up of the cluster or something else? I get this error for both the single and paired example data.

Thank you for your time

**Comment by mrtnbns** [comment]
Hi,

could you provide the content of `/flush1/bac050/FRAMA/example/paired/output/logs/000_software_check.log` and `/flush1/bac050/FRAMA/example/paired/output/logs/054_blast_trin2cds.log`?

Did you run `SETUP.pl` in `setup` initially? Maybe BLAST or genblastA are not installed. Your version of perl is fine.

**Comment by Andy-B-123** [comment]
Hi, thank you for the fast reply. 

I re-ran SETUP.pl before starting today just to make sure and everything except UniVec_Core was installed properly.

Attached files: 
[000_software_check.log](https://github.com/gengit/FRAMA/files/1745828/000_software_check.log)
[054_blast_trin2cds.log](https://github.com/gengit/FRAMA/files/1745830/054_blast_trin2cds.log)

In the 054_blast_trin2cds.log file it says 
```
cat: /flush1/bac050/FRAMA/example/paired/output/blast/_tmp_SGE_34853/SGE_34853_input.0.blast: No such file or directory
cat: /flush1/bac050/FRAMA/example/paired/output/blast/_tmp_SGE_34853/SGE_34853_input.1.blast: No such file or directory
cat: /flush1/bac050/FRAMA/example/paired/output/blast/_tmp_SGE_34853/SGE_34853_input.2.blast: No such file or directory
cat: /flush1/bac050/FRAMA/example/paired/output/blast/_tmp_SGE_34853/SGE_34853_input.3.blast: No such file or directory
cat: /flush1/bac050/FRAMA/example/paired/output/blast/_tmp_SGE_34853/SGE_34853_input.4.blast: No such file or directory
```

but these files in that directory do not have the `.blast`. Files in the _tmp_SGE_34853 directory: 

```
/flush1/bac050/FRAMA/example/paired/output/blast/_tmp_SGE_34853/SGE_34853_input.4
/flush1/bac050/FRAMA/example/paired/output/blast/_tmp_SGE_34853/SGE_34853_input.3
/flush1/bac050/FRAMA/example/paired/output/blast/_tmp_SGE_34853/SGE_34853_input.2
/flush1/bac050/FRAMA/example/paired/output/blast/_tmp_SGE_34853/SGE_34853_input.1
/flush1/bac050/FRAMA/example/paired/output/blast/_tmp_SGE_34853/SGE_34853_input.0
/flush1/bac050/FRAMA/example/paired/output/blast/_tmp_SGE_34853/SGE_34853_commands.sh
```

Not sure if that could be reason? Or how I could fix that

**Comment by mrtnbns** [comment]
Hi, thanks for the log files. `000_software_check.log` shows that the the error is definitely caused by a missing BLAST version that is required for GENBLASTa. During the installation you should have gotten an error? NCBI seems to have changed the ftp link from `ftp://ftp.ncbi.nlm.nih.gov/blast/executables/legacy/2.2.16/blast-2.2.16-x64-linux.tar.gz` to `ftp://ftp.ncbi.nlm.nih.gov/blast/executables/legacy.NOTSUPPORTED/2.2.16/blast-2.2.16-x64-linux.tar.gz`, recently. 

I will check that, but it may take a while until I can report back. Until then, you could change the link yourself by replacing `ftp://ftp.ncbi.nlm.nih.gov/blast/executables/legacy/2.2.16/blast-2.2.16-x64-linux.tar.gz` in `setup/programs.yaml` (line 15) to `ftp://ftp.ncbi.nlm.nih.gov/blast/executables/legacy.NOTSUPPORTED/2.2.16/blast-2.2.16-x64-linux.tar.gz`.

Thank for reporting,
Martin

**Comment by Andy-B-123** [comment]
Hi thank you for the info! I don't have access to the cluster over the weekend but I will do that on Monday and update. No rush to get back! Thank you for the instructions.

Cheers,

Andy

**Comment by Andy-B-123** [comment]
Update: Changed the line on a FRAMA version I am running locally and it works. Thank you for your help, much appreciated!
